#apidoc
apidoc: true
api:
  md5: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.94.208.59:8761/eureka/

spring:
    application:
          name: eurka-gather
    datasource:
          name: mysql_test
        # 报错，先注释掉他。
        #type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
#        druid:
          #监控统计拦截的filters
#          default-auto-commit: false
#          auto-commit: false
          filters: stat
          driver-class-name: com.mysql.cj.jdbc.Driver
          #基本属性
          url: jdbc:mysql://47.94.208.59:33306/jihe?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&nullCatalogMeansCurrent=true
          username: root
          password: L@cc12345
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.winterchen.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

mybatis:
  configuration:
    map-underscore-to-camel-case: true

#log
logging:
  file: info2.log
  level:
    root: INFO
    com: trace
    org: ERROR
    net: ERRORR
    io: ERROR


flowable:
  check-process-definitions: false
  #db-identity-used: true
  # 自动生成flowable相关表 第一次生成后建议关闭提高运行速度
  #database-schema-update: true
  # 保存历史数据级别设置为full最高级别，便于历史数据的追溯
  history-level: full
  #关闭定时任务JOB
  async-executor-activate: false